<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>LegatoBase.Common</AssemblyName>
        <RootNamespace>LegatoBase.Common</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../core/core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="OneOf" Version="3.0.271" />
    </ItemGroup>
    
</Project>
