<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Legatobase.API</AssemblyName>
        <RootNamespace>Legatobase.API</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../core/core.csproj" />
        <ProjectReference Include="../common/common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AdysTech.CredentialManager" Version="3.1.0" />
      <PackageReference Include="FluentHttpClient" Version="5.0.2" />
      <PackageReference Include="OneOf" Version="3.0.271" />
    </ItemGroup>

</Project>
